config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  
  root 'tweets#index'
  
  resources :tweets do
    resources :comments, only: [:new, :create]
    resources :likes, only: [:create, :destroy]
    resources :views, only: [:create]
  end
  
  resources :users, only: [:show, :edit, :update]
  
  get '/box/new' => 'opinions#new'
  post '/box/create' => 'opinions#create'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
  
  [:text, :tweet_id, :user_id].each do |v|
    validates v, presence: true
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  [:text, :user_id].each do |v|
    validates v, presence: true
  end
  
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  
  belongs_to :user
  has_many :comments
  has_many_attached :images
  has_many :likes, dependent: :destroy
  has_many :views, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  
  [:title, :currency_pair, :images, :text].each do |v|
    validates v, presence: true
  end

end

app/models/user.rb
class MyValidator < ActiveModel::Validator
  def validate(record)
  end
end

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :authentication_keys => [:nickname]
         
  has_many :tweets
  has_many :comments
  has_many :commented_tweets, through: :comments, source: :tweet
  has_many :likes
  has_many :views
  has_many :liked_tweets, through: :likes, source: :tweet
  has_one_attached :image
  
  validates :nickname, 
  presence: true, uniqueness: true, 
  length: {maximum: 8}, format: { with: /\A[a-z0-9]+\z/i }
  
  validates :age,
  numericality: {only_integer: true}, on: :update
  
  def changed_profile?(update_params)
    self.attributes = update_params
    
    if self.changed? && self.valid?
      true
    else
      false
    end
  end
  
  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
  
  def already_watched?(tweet)
    self.views.exists?(tweet_id: tweet.id)
  end
  def email_required?
    false
  end
  
  def email_changed?
    false
  end
  
  def will_save_change_to_email?
    false
  end
  
end

app/models/view.rb
class View < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    Comment.create(create_params)
  end
  
  private
  def create_params
    params.permit(:text).merge(tweet_id: params[:id], user_id: current_user.id)
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
  def create
    @like = Like.create(tweet_id: params[:tweet_id], user_id: current_user.id)
    redirect_back(fallback_location: root_path)
  end
  
  def destroy
    @like = Like.find_by(user_id: current_user.id, tweet_id: params[:tweet_id])
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
  
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  
  def new
  end
  
  def create
    Opinion.create(create_params)
  end
  
  private
  def create_params
    params.permit(:text).merge(user_id: current_user.id)
  end
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  layout 'form', only: [:new, :edit]
  before_action :user_confirm, only: [:new]
  
  def index
    @tweets = Tweet.includes(:user).with_attached_images.order('updated_at DESC').page(params[:page]).per(10)
  end
  
  def create
    @tweet = Tweet.new
    @tweet.attributes = update_params
    
    if @tweet.valid?
      Tweet.create(update_params)
      redirect_to :root, :alert => "Created your tweet!"
    else
      render "edit.html.erb", object: @tweet, layout: 'form'
    end
  end
  
  def new
    @tweet = Tweet.new
  end
  
  def edit
    @tweet = Tweet.find(params[:id])
  end
  
  def show
    @tweet = Tweet.find(params[:id])
  end
  
  def update
    @tweet = Tweet.find(params[:id])
    @tweet.attributes = update_params
    
    if @tweet.changed? && @tweet.valid?
      @tweet.update(update_params)
      redirect_to :root, :notice => "Updated! your tweet!"
    else
      flash[:message] = "Nothing has changed..."
      render 'edit', object: @tweet, layout: 'form'
    end
  end
  
  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    flash[:message] = "Deleted!"
    redirect_to :root
  end
  
  private
  def update_params
    params.require(:tweet).permit(:title, :text, :currency_pair, images: []).merge(user_id: current_user.id)
  end
  
  def user_confirm
    if user_signed_in?
      true
    else
      flash[:alert] = "If you want to create your tweet, please sign in!"
      redirect_to new_user_session_path
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]
  layout 'devise'
  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:nickname])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user_profile = User.find(params[:id])
    @user_tweets = @user_profile.tweets.page(params[:page]).per(5)
  end
  
  def edit
    @user_profile = User.find(params[:id])
  end
  
  def update
    @user_profile = User.find(params[:id])
    
    if @user_profile.changed_profile?(update_params) && @user_profile.valid?
      @user_profile.update(update_params)
      flash[:message] = "Updated your profile!"
      redirect_to user_path(current_user.id)
    else
      @user_profile.attributes = update_params

      if @user_profile.valid?
        flash.now[:message] = "Nothing has changed..."
        render "edit.html.erb", object: @user_profile
      else
        render "edit.html.erb", object: @user_profile
      end
    end
      
    
    # user_profile.attributes = update_params
    
    # if user_profile.changed? && user_profile.valid?
    #   user_profile.update(update_params)
    #   redirect_to user_path(current_user.id), alert: "Updated your profile!"
    # else
    #   redirect_to edit_user_path(current_user.id), alert: "Update failure!"
    # end
  end
  
  private
  def update_params
    params.require(:user).permit(:nickname, :image, :age, :gender, :nationality, :self_introduction)
  end
end

app/controllers/views_controller.rb
class ViewsController < ApplicationController
  
  def create
    View.create(tweet_id: params[:tweet_id], user_id: current_user.id)
    redirect_to controller: 'tweets', action: 'show', id: "#{params[:tweet_id]}"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/views_helper.rb
module ViewsHelper
end

app/views/tweets/_form.html.erb
<%= form_for tweet, local: true do |f| %>
 <div class="select-currency-field">
    <%= f.label :currency_pair %><br>
    <%= f.select :currency_pair, ["USDJPY", "GBPJPY", "EURJPY", "GBPUSD", "EURUSD", "BTCJPY", "BTCUSD", "Others"], :prompt => "Select" %><br>
  </div>
  <div class="images-field">
    <%= f.label :images %><br>
    <%= f.file_field :images, multiple: true %><br>
  </div>
  <div class="text-field">
    <%= f.label :text %><br>
    <%= f.text_area :text, style: "margin: 0px; width: 728px; height: 241px; max-width: 728px; min-width: 728px", value: tweet.text %><br>
  </div>
  <%= f.submit "Submit", data: {confirm: "Do you want to submit?"} %><br>
  <small><%= link_to 'Back to home', root_path, method: :get %></small>
<% end %>

app/views/tweets/_store.html.erb
<% tweets.each do |tweet| %>
  <div class="container">
    <div class="tweet-title">
      <h2>
        <span style="border-bottom: solid 1px gray;">
          <% if current_user.already_watched?(tweet) %>
            <%= link_to "#{tweet.title}", tweet_path(tweet.id), method: :get %>
          <% else %>
            <%= link_to "#{tweet.title}", tweet_views_path(tweet.id), method: :post %>
          <% end %>
        </span>
      </h2>
      <small style="color: black;">
        📰<time datetime="<%= tweet.updated_at %>">Updated at <%= tweet.updated_at %></time> by <%= link_to "#{tweet.user.nickname}", user_path(tweet.user_id), method: :get, style: "text-decoration: underline; color: black;" %>
      </small>
      <div class="rate-box">
        <% if current_user.already_liked?(tweet) %>
          <small class="liked-users"><span><%= link_to '👍', "/tweets/#{tweet.id}/likes/#{tweet.likes.find_by(user_id: current_user.id).id}", method: :delete %></span>: <u><%= tweet.likes.count %> (You +1)</u></small>
        <% else %>
          <small class="liked-users"><span><%= link_to '👍', tweet_likes_path(tweet), method: :post %></span>: <u><%= tweet.likes.count %></u></small>
        <% end %>
        <small class="commented-users"><%= link_to '💬', '/', method: :get %>: <u><%= tweet.comments.count %></u></small>
        <% if current_user.already_watched?(tweet) %>
          <small class="watched-counts">👁: <u><%= tweet.views.count %> (You +1)</u></small>
        <% else %>
          <small class="watched-^counts">👁: <u><%= tweet.views.count %></u></small>
        <% end %>
      </div>
    </div>
    <div class="currency_pair">
      <h3><%= tweet.currency_pair %></h3>
      <% unless tweet.currency_pair == "Others" %>
        <%= image_tag "#{tweet.currency_pair[0,3]}.png", class: "currency" %>
        <%= image_tag "#{tweet.currency_pair[3,6]}.png", class: "margin_currency" %>
      <% end %>
    </div>
    <ul class="tweet-btn">
      <li>▼</li>
      <ul>
        <li><%= link_to 'Detail', tweet_path(tweet.id), method: :get %></li>
        <% if user_signed_in? && current_user.id == tweet.user_id %>
          <li><%= link_to 'Edit', edit_tweet_path(tweet.id), method: :get %></li>
          <li><%= link_to 'Delete', tweet_path(tweet.id), data: {confirm: "Do you want to delete?"}, method: :delete %></li>
        <% end %>
      </ul>
    </ul>
    <% if tweet.images.attached? %>
      <div class="slick">
        <% tweet.images.each do |image| %>
          <%= image_tag image %>
        <% end %>
      </div>
    <% end %>
    <div class="text">
      <%= simple_format(tweet.text) %>
    </div>
    <div class="poster-nickname">
      <small style="color: black;">Poster : <%= link_to "#{tweet.user.nickname}", user_path(tweet.user.id), method: :get, style: "color: black; text-decoration: underline;"%></small>
    </div>
　</div>
<% end %>

app/views/tweets/delete.html.erb
<p>Do you delete?</p>
<ul>
  <li>YES</li>
  <li><%= link_to 'NO', root_path, method: :get %></li>
</ul>

app/views/tweets/edit.html.erb
<%= render partial: 'commons/form', object: @tweet, object: flash %>

app/views/tweets/index.html.erb
<article>
  <%= render partial: 'commons/flash', object: flash %>
  <%= paginate @tweets, turbolinks: false %>
  <%= render partial: 'commons/tweet', locals: {tweets: @tweets} %>
  <%= paginate @tweets %>
</article>

app/views/tweets/new.html.erb
<%= render partial: "commons/form", locals: {tweet: @tweet} %>

app/views/tweets/show.html.erb
<article id="show">
  <div class="container">
    <div class="currency-pair">
      <h3><%= @tweet.currency_pair %></h3>
      <% unless @tweet.currency_pair == "Others" %>
        <%= image_tag "#{@tweet.currency_pair[0,3]}.png", class: "currency" %>
        <%= image_tag "#{@tweet.currency_pair[3,6]}.png", class: "margin-currency" %>
      <% end %>
    </div>
    <div class="tweet-title">
      <h2>
        <span style="border-bottom: solid 1px gray;">
          <% if current_user.already_watched?(@tweet) %>
            <%= link_to "#{@tweet.title}", tweet_path(@tweet.id), method: :get %>
          <% else %>
            <%= link_to "#{@tweet.title}", tweet_views_path(@tweet.id), method: :post %>
          <% end %>
        </span>
      </h2>
      <small style="color: black;">
        📰<time datetime="<%= @tweet.updated_at %>">Updated at <%= @tweet.updated_at %></time> by <%= link_to "#{@tweet.user.nickname}", user_path(@tweet.user_id), method: :get, style: "text-decoration: underline; color: black;" %>
      </small>
      <div class="rate-box">
        <% if current_user.already_liked?(@tweet) %>
          <small class="liked-users"><span><%= link_to '👍', "/tweets/#{@tweet.id}/likes/#{@tweet.likes.find_by(user_id: current_user.id).id}", method: :delete %></span>: <u><%= @tweet.likes.count %> (You +1)</u></small>
        <% else %>
          <small class="liked-users"><span><%= link_to '👍', tweet_likes_path(@tweet), method: :post %></span>: <u><%= @tweet.likes.count %></u></small>
        <% end %>
        <small class="commented-users"><%= link_to '💬', '/', method: :get %>: <u><%= @tweet.comments.count %></u></small>
        <% if current_user.already_watched?(@tweet) %>
          <small class="watched-counts">👁: <u><%= @tweet.views.count %> (You +1)</u></small>
        <% else %>
          <small class="watched-^counts">👁: <u><%= @tweet.views.count %></u></small>
        <% end %>
      </div>
    </div>
    <ul class="tweet-btn">
      <li>▼</li>
      <ul>
        <% if user_signed_in? && current_user.id == @tweet.user_id %>
          <li><%= link_to 'Edit', edit_tweet_path(@tweet.id), method: :get %></li>
          <li><%= link_to 'Delete', tweet_path(@tweet.id), data: {confirm: "Do you want to delete?"}, method: :delete %></li>
        <% end %>
      </ul>
    </ul>
    <% if @tweet.images.attached? %>
      <div class="slick">
        <% @tweet.images.each do |image| %>
          <%= image_tag image %>
        <% end %>
      </div>
    <% end %>
    <div class="text">
      <%= simple_format(@tweet.text) %>
    </div>
    <div class="poster-nickname">
      <small style="color: black;">Poster : <%= link_to "#{@tweet.user.nickname}", user_path(@tweet.user.id), method: :get, style: "color: black; text-decoration: underline;"%></small>
    </div>
　</div>
</article>